### ISSUE TITLE
Typo in line 156

### ISSUE THREAD

**Issue by mroorda** [dylanbeeber/crispRdesignR#1]
Hi Dylan,

I'm here to inform you there is a typo in the `sgRNA_design()`. On line 156, it reads `Efficency_score`, but this should read `Efficiency_score`. There were some other minor quirks that I had to manually change in the function, but that might as well have been product of my own tinkering around with the code.

**Comment by dylanbeeber** [comment]
Thank you for pointing this out - corrected!
